Issue/6
jeKnowledge/dotworks pull request #18
Opened 2016-10-12 14:03 UTC by Joaquim-Ferrer

2016-10-13 16:56 UTC, mmachado95 requested changes
Only need to change the Portuguese to English.

2016-10-13 16:56 UTC, Kabombom commented on dotworks/dotworks_server/forms.py
> +        label="Password antiga",
We need to start using english. So it's best to already change labels to english

2016-10-13 16:56 UTC, Kabombom commented on dotworks/dotworks_server/forms.py
> +        label="Nova password",
Same as above

2016-10-13 16:56 UTC, Kabombom commented on dotworks/dotworks_server/forms.py
> +        label="Confirmar nova password",
Same as above

2016-10-13 16:56 UTC, Kabombom commented on dotworks/dotworks_server/templates/change_password_page.html
> +        <input type="submit" value="Submeter" />
Same as above

2016-10-14 00:49 UTC, Joaquim-Ferrer commented
Done.

2016-10-14 01:11 UTC, merged